# Generated by Django 4.1 on 2024-07-28 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0002_alter_branch_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='institution_number',
            field=models.CharField(default='UNKNOWN_INST_NUM', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
